trigger:
- main

pool:
  name: flm-pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: echo hello ashok
  displayName: ashok

- script: echo this is running in flm pool 
  displayName: flm-pool